import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import Footer from '@/components/footer';

const openSans = Open_Sans({
	subsets: ['latin'],
	display: 'swap',
});


export const metadata: Metadata = {
	title: 'Tickete',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={openSans.className}>
				{children}
				<Footer />
			</body>
		</html>
	);
}
